##micronaut:
##  application:
##    name: veiculoMs
##datasources:
##  default:
##    driverClassName: org.postgresql.Driver
##    db-type: postgresql
##    schema-generate: CREATE_DROP
##    dialect: POSTGRES
##netty:
##  default:
##    allocator:
##      max-order: 3
##jpa.default.properties.hibernate.hbm2ddl.auto: update
