micronaut:
  application:
    name: relatorioMs
  server:
    port: -1

mongodb:
  uri: 'mongodb://localhost:27017/venda'

consul:
  client:
    resitration:
      enabled: true
    defaultZone: "localhost:8500"