micronaut:
  application:
    name: lojaMs
  server:
    port: 8081

kafka:
  bootstrap:
    servers: localhost:9092


consul:
  client:
    resitration:
      enabled: true
    defaultZone: "localhost:8500"